### PR TITLE
update AFL++

### PR DESCRIPTION
**Pull request by vanhauser-thc**
sorry to bother, for a feature in https://github.com/srlabs/ziggy that my team and me needs I added a feature in AFL++.
If you would be so kind to merge this before doing a new release that would be perfect.
(it adds an env var trigger that allows skipping over -i seeds that run into a timeout instead of afl-fuzz exiting.)
Thanks!

### CODE REVIEW

**Comment by smoelius** [comment]
Would it meet your needs if I published a release with this update but not the new `system-config` subcommand?

**Comment by vanhauser-thc** [comment]
Yes that would be fine, thanks!
system-config is „just“ for helping normal users, I don’t need that :)

**Comment by smoelius** [comment]
Published in [0.13.5](https://github.com/rust-fuzz/afl.rs/tree/0.13.5)

**Comment by vanhauser-thc** [comment]
thank you!

**Pull request merged**
