### PR TITLE
Upgrade to using AFLplusplus

### PR DESCRIPTION
**Pull request by binarybana**
Here I'm using a submodule, but happy to switch to fully vendoring AFL++ if that's preferred.

### CODE REVIEW

**Comment by binarybana** [comment]
Hmm.. will need to grab a mac machine to debug the build error on that platform apparently.

**Comment by frewsxcv** [comment]
your branch works for me on my macbook! not sure what's going on in CI...

**Comment by frewsxcv** [comment]
okay switched away from travis CI to github actions 🙃

**Comment by frewsxcv** [comment]
ironically now linux fails and mac passes

**Comment by binarybana** [comment]
Thanks for the great tool/crate and for taking my PR over the line!

**Pull request merged**
