### PR TITLE
add addseeds command

### PR DESCRIPTION
**Pull request by vanhauser-thc**
adds the addseeds command

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@smoelius can we merge this? it is tiny and useful :)

**Comment by smoelius** [comment]
Sorry for not responding. I think the green check marks are deceiving us, because `addseeds` is not in the version of AFLplusplus that afl.rs currently uses.

Arguably, this is a failure of afl.rs's CI, which should check whether commands like `cargo afl addseeds` succeed. (Currently, it only checks their stdout/stderr.)

Before merging, I would like to fix CI, and then rebase this PR onto that. Please give me another day or so.

**Comment by smoelius** [comment]
Thank you very much for the fix related to #410.

Could you please rebase this branch?

**Comment by vanhauser-thc** [comment]
Done

**Comment by smoelius** [comment]
Thank you, @vanhauser-thc.

**Pull request merged**
